const STORAGE_KEY = 'mente-mapa-v1';
const MAP = { width: 1200, height: 680, minZoom: .5, maxZoom: 1.5, step: .1 };
const $ = (selector) => document.querySelector(selector);
const canvas = $('#canvas'), graph = $('#constellation'), layer = $('#nodesLayer'), svg = $('#connections');
const ui = { input: $('#ideaInput'), count: $('#nodeCount'), zoom: $('#zoomLevel'), empty: $('#emptyState'), editor: $('#nodeEditor'), title: $('#editTitle'), description: $('#editDescription'), label: $('#detailLabel'), connectionCount: $('#connectionCount'), target: $('#connectionTarget'), related: $('#relatedList'), importer: $('#importFile'), onboarding: $('#onboarding') };
let selectedId = null;
let dragging = null;
let view = { zoom: .88, x: -72, y: -24 };
let data = load();

function defaultMap() { return { nodes: [{ id: crypto.randomUUID(), title: 'Compreensão', description: 'O ponto de partida para organizar o que importa.', x: 510, y: 265, root: true }], connections: [] }; }
function load() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return saved?.nodes && saved?.connections ? saved : defaultMap(); } catch { return defaultMap(); } }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }
function node(id) { return data.nodes.find((item) => item.id === id); }
function connected(id) { return data.connections.filter((link) => link.from === id || link.to === id).map((link) => link.from === id ? link.to : link.from); }
function renderView() { graph.style.transform = `translate3d(${view.x}px, ${view.y}px, 0) scale(${view.zoom})`; ui.zoom.textContent = `${Math.round(view.zoom * 100)}%`; }
function resetView() { view = window.matchMedia('(max-width: 650px)').matches ? { zoom: .65, x: -260, y: -65 } : { zoom: .88, x: -72, y: -24 }; renderView(); }
function render() { renderNodes(); renderConnections(); renderPanel(); ui.count.textContent = `${data.nodes.length} ${data.nodes.length === 1 ? 'ideia' : 'ideias'}`; save(); }
function renderNodes() { layer.replaceChildren(...data.nodes.map((item) => { const button = document.createElement('button'); button.type = 'button'; button.className = `node user-node ${item.root ? 'root' : ''} ${item.id === selectedId ? 'is-selected' : ''}`; button.dataset.id = item.id; button.style.left = `${item.x}px`; button.style.top = `${item.y}px`; button.setAttribute('aria-pressed', String(item.id === selectedId)); button.innerHTML = `<strong>${escapeHtml(item.title)}</strong><small>${item.root ? 'ideia central' : 'clique para editar'}</small>`; button.addEventListener('click', () => select(item.id)); button.addEventListener('pointerdown', startNodeDrag); return button; })); }
function renderConnections() { svg.replaceChildren(...data.connections.map((link) => { const from = node(link.from), to = node(link.to); if (!from || !to) return document.createDocumentFragment(); const line = document.createElementNS('http://www.w3.org/2000/svg', 'line'); line.setAttribute('x1', from.x + 80); line.setAttribute('y1', from.y + 42); line.setAttribute('x2', to.x + 80); line.setAttribute('y2', to.y + 42); line.classList.toggle('is-related', selectedId === link.from || selectedId === link.to); return line; })); }
function renderPanel() { const item = node(selectedId); ui.empty.hidden = Boolean(item); ui.editor.hidden = !item; if (!item) return; ui.label.textContent = item.root ? 'IDEIA CENTRAL' : 'IDEIA'; ui.title.value = item.title; ui.description.value = item.description; const ids = connected(item.id); ui.connectionCount.textContent = `${ids.length} ${ids.length === 1 ? 'conexão' : 'conexões'}`; ui.target.replaceChildren(...data.nodes.filter((other) => other.id !== item.id && !ids.includes(other.id)).map((other) => new Option(other.title, other.id))); $('#connectNode').disabled = ui.target.options.length === 0; ui.related.replaceChildren(...ids.map((id) => { const other = node(id), row = document.createElement('span'); const go = document.createElement('button'), remove = document.createElement('button'); go.type = remove.type = 'button'; go.textContent = other.title; go.addEventListener('click', () => select(id)); remove.textContent = '×'; remove.className = 'remove-link'; remove.setAttribute('aria-label', `Remover conexão com ${other.title}`); remove.addEventListener('click', () => { data.connections = data.connections.filter((link) => !((link.from === item.id && link.to === id) || (link.to === item.id && link.from === id))); render(); }); row.append(go, remove); return row; })); }
function select(id) { selectedId = id; render(); }
function addIdea() { const text = ui.input.value.trim(); if (!text) { ui.input.focus(); return; } const [firstLine, ...rest] = text.split('\n'); const title = firstLine.slice(0, 80); const description = rest.join('\n').trim() || text; const count = data.nodes.length; const item = { id: crypto.randomUUID(), title, description, x: 170 + (count * 117) % 760, y: 110 + (count * 93) % 430, root: false }; data.nodes.push(item); ui.input.value = ''; select(item.id); }
function startNodeDrag(event) { if (event.button !== 0) return; const id = event.currentTarget.dataset.id; dragging = { type: 'node', id, startX: event.clientX, startY: event.clientY, x: node(id).x, y: node(id).y, moved: false }; event.currentTarget.setPointerCapture(event.pointerId); event.stopPropagation(); }
function startPan(event) { if (event.target.closest('.node') || event.button !== 0) return; dragging = { type: 'map', startX: event.clientX, startY: event.clientY, x: view.x, y: view.y }; canvas.setPointerCapture(event.pointerId); }
function move(event) { if (!dragging) return; const dx = event.clientX - dragging.startX, dy = event.clientY - dragging.startY; if (dragging.type === 'map') { view.x = dragging.x + dx; view.y = dragging.y + dy; renderView(); return; } const item = node(dragging.id); dragging.moved ||= Math.abs(dx) + Math.abs(dy) > 4; item.x = Math.max(0, Math.min(MAP.width - 160, dragging.x + dx / view.zoom)); item.y = Math.max(0, Math.min(MAP.height - 84, dragging.y + dy / view.zoom)); renderNodes(); renderConnections(); }
function stopDrag() { if (!dragging) return; if (dragging.type === 'node' && dragging.moved) save(); dragging = null; }
function changeZoom(amount, point) { const next = Math.max(MAP.minZoom, Math.min(MAP.maxZoom, view.zoom + amount)); if (next === view.zoom) return; const rect = canvas.getBoundingClientRect(), p = point || { x: rect.width / 2, y: rect.height / 2 }; const mx = (p.x - view.x) / view.zoom, my = (p.y - view.y) / view.zoom; view.zoom = next; view.x = p.x - mx * next; view.y = p.y - my * next; renderView(); }
function escapeHtml(text) { const div = document.createElement('div'); div.textContent = text; return div.innerHTML; }

$('#addIdea').addEventListener('click', addIdea); ui.input.addEventListener('keydown', (event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); addIdea(); } }); $('#newIdea').addEventListener('click', () => { ui.input.focus(); ui.input.scrollIntoView({ behavior: 'smooth', block: 'center' }); });
ui.editor.addEventListener('submit', (event) => { event.preventDefault(); const item = node(selectedId); item.title = ui.title.value.trim() || 'Ideia sem título'; item.description = ui.description.value.trim(); render(); });
$('#deleteNode').addEventListener('click', () => { const item = node(selectedId); if (!item || !confirm(`Excluir “${item.title}” e suas conexões?`)) return; data.nodes = data.nodes.filter((entry) => entry.id !== item.id); data.connections = data.connections.filter((link) => link.from !== item.id && link.to !== item.id); selectedId = null; render(); });
$('#connectNode').addEventListener('click', () => { if (!selectedId || !ui.target.value) return; data.connections.push({ from: selectedId, to: ui.target.value }); render(); });
$('#clearMap').addEventListener('click', () => { if (!confirm('Limpar todo o mapa? Esta ação não pode ser desfeita.')) return; data = { nodes: [], connections: [] }; selectedId = null; render(); });
$('#exportMap').addEventListener('click', () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = 'mente-mapa.json'; link.click(); URL.revokeObjectURL(url); });
$('#importMap').addEventListener('click', () => ui.importer.click()); ui.importer.addEventListener('change', async () => { const file = ui.importer.files[0]; if (!file) return; try { const imported = JSON.parse(await file.text()); if (!Array.isArray(imported.nodes) || !Array.isArray(imported.connections)) throw new Error(); data = imported; selectedId = null; render(); } catch { alert('Arquivo inválido. Selecione um mapa Mente Mapa em JSON.'); } finally { ui.importer.value = ''; } });
$('#resetView').addEventListener('click', resetView); $('#zoomIn').addEventListener('click', () => changeZoom(MAP.step)); $('#zoomOut').addEventListener('click', () => changeZoom(-MAP.step)); canvas.addEventListener('pointerdown', startPan); canvas.addEventListener('pointermove', move); canvas.addEventListener('pointerup', stopDrag); canvas.addEventListener('pointercancel', stopDrag); canvas.addEventListener('wheel', (event) => { event.preventDefault(); const rect = canvas.getBoundingClientRect(); changeZoom(event.deltaY > 0 ? -.08 : .08, { x: event.clientX - rect.left, y: event.clientY - rect.top }); }, { passive: false }); canvas.addEventListener('keydown', (event) => { if (event.key === '+' || event.key === '=') changeZoom(MAP.step); if (event.key === '-') changeZoom(-MAP.step); if (event.key.toLowerCase() === 'r') resetView(); }); $('#dismissOnboarding').addEventListener('click', () => { ui.onboarding.hidden = true; localStorage.setItem(`${STORAGE_KEY}-onboarding`, 'done'); }); if (localStorage.getItem(`${STORAGE_KEY}-onboarding`) === 'done') ui.onboarding.hidden = true;
resetView(); render();
